apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-practice-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/ci-cd_project.git' # Replace with your repo
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
      include: ["dev.yaml"]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
