apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-practice-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-practice-app
  template:
    metadata:
      labels:
        app: devops-practice-app
    spec:
      containers:
      - name: app
        image: devops-practice-app:latest # Replace with registry/image:tag
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: devops-practice-app
  namespace: prod
spec:
  selector:
    app: devops-practice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
